baseURL = 'https://axon-rl.github.io/'
languageCode = 'en-us'
title = 'Axon-RL - Wiring General Intelligence Through Reinforcement Learning'

[params]
  description = "Advancing the frontiers of artificial intelligence through innovative reinforcement learning research and development."
  github_url = "https://github.com/axon-rl"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false